### PR TITLE
correct `setup_anndata` load

### PR DESCRIPTION
**Pull request by abearab**

### CODE REVIEW

**Comment by adamgayoso** [comment]
Can you describe what you've fixed here? Thanks!

**Comment by abearab** [comment]
Yes, 
This is the way it's noted in the online notebook 

```
scvi.model.SCVI.setup_anndata
```

But it is coming from a different place in your implementation, right? If not, I may have an older versions 🤔

**Comment by adamgayoso** [comment]
It has been this way for a few versions now, you can always select the version of the docs for the version you have at the bottom left corner of the docs site.

**Comment by adamgayoso** [comment]
But also I recommend upgrading!

**Comment by abearab** [comment]
Yeah, I'm wrong then! Sorry about the incorrect pull request 👎 

I have version `0.13` from `bioconda` channel. So I should update surely and switch to the `conda-forge`. Thanks for your help.

**Pull request closed without merging**
