### PR TITLE
Update mpl version to fix mde issue

### PR DESCRIPTION
**Pull request by RK900**

### CODE REVIEW

**Comment by jjhong922** [comment]
we would want to fix this in pyproject.toml to fix all cases of this, not just in this tutorial. Also, I'm not convinced that this is a widespread error. Have you tried installing the highest version of 3.4 and testing it?

**Comment by RK900** [comment]
i tried 3.4, error on cell 16

`ImportError: cannot import name '_png' from 'matplotlib' (/usr/local/lib/python3.7/dist-packages/matplotlib/__init__.py)`

**Comment by jjhong922** [comment]
The error changes? That's not a good sign. There's likely something else that is at the bottom of this issue.

**Comment by RK900** [comment]
Just as a sanity check, I reran the unmodified notebook and it had no errors.

**Comment by cane11** [comment]
It looks like a Colab issue. Matplotlib is imported on start of a Colab session. You have to restart the notebook when you update Matplotlib.

**Comment by RK900** [comment]
Agreed, I think it's just a colab versioning issue.

**Pull request closed without merging**
